services:
  - type: web
    name: smm-free-panel
    runtime: node
    plan: free
    buildCommand: cd backend && npm install && npx prisma generate
    startCommand: cd backend && npm start
    preDeployCommand: cd backend && npx prisma db seed
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
